// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table fabricevents (id:string, subject:string, ['time']:string, specversion:string, datacontenttype:string, source:string, type:string, dataschemaversion:string, data:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
